name: strategy-alert

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install requests pandas pyyaml tvdatafeed matplotlib

      - name: Run monitor
        env:
          DING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        run: |
          python alert_monitor.py
